### ISSUE TITLE
Prayer times as date objects

### ISSUE THREAD

**Issue by uxai** [islamic-network/api.aladhan.com#44]
Salaam!
It would be great if  the prayer times could also be returned as date objects.

Currently they are returned just as a string. The problem comes with midnight, whereby the time could be before 12AM or after, and even as late as 1am. This causes issues with countdown as it thinks midnight is today at AM instead of tomorrow.

Ideally we would have returned for prayer times today:

```
August 03, 2021 5:20AM (fajr)
...
August 03, 2021 8:20PM (for isha)
August 04, 2021 1:20AM (for midnight)
```

Thanks!

**Comment by meezaan** [comment]
Alaykum Al alaam @uxai.

This is already possible (albeit not exactly in the format you are after), but it appears I did not update the documentation.

The API returns an iso8601 compliant datetime string (which you can parse as an object) for prayer times if you append iso8601=true as a query parameter to your API call.

So http://api.aladhan.com/v1/timingsByCity?city=Algiers&country=Algeria&method=4&school=0&iso8601=true will return timings in the following format:
```
{
  "code": 200,
  "status": "OK",
  "data": {
    "timings": {
      "Fajr": "2021-08-04T04:13:00+01:00",
      "Sunrise": "2021-08-04T05:56:00+01:00",
      "Dhuhr": "2021-08-04T12:54:00+01:00",
      "Asr": "2021-08-04T16:42:00+01:00",
      "Sunset": "2021-08-04T19:51:00+01:00",
      "Maghrib": "2021-08-04T19:51:00+01:00",
      "Isha": "2021-08-04T21:21:00+01:00",
      "Imsak": "2021-08-04T04:03:00+01:00",
      "Midnight": "2021-08-04T00:54:00+01:00"
    },
...
```

Insha Allah I hope this helps.

**Comment by uxai** [comment]
Thanks for this method! 
but as you can see with the output below you may see here a similar issue I mentioned, where midnight is put as todays date when it should be tomorrow since it is past 12AM in this case.

Of course, I can add one day now easily if the hours is < 2, but the enhancement would be nice to be received already adjusted :)


```
Asr: "2021-08-04T16:32:00+08:00 (+08)"
Dhuhr: "2021-08-04T13:10:00+08:00 (+08)"
Fajr: "2021-08-04T05:54:00+08:00 (+08)"
Imsak: "2021-08-04T05:44:00+08:00 (+08)"
Isha: "2021-08-04T20:11:00+08:00 (+08)"
Maghrib: "2021-08-04T19:31:00+08:00 (+08)"
Midnight: "2021-08-04T01:10:00+08:00 (+08)"
Sunrise: "2021-08-04T07:05:00+08:00 (+08)"
```

**Comment by meezaan** [comment]
Okay I think you are making the underlying assumption here that midnight belongs to the next calendar day, that is, what is coming after Isha.

But it is possible that it actually belongs to the calendar day in question, that is, the midnight preceding Imsak, in which case there is no change required.

I'll actually have to check the underlying code.

Watch this space.

**Comment by uxai** [comment]
Thanks, I think it would be super helpful if I fetch todays dates it still includes midnight but the date is just put for the next day when necessary, rather than asking to fetch the next day too in the case of midnight being the following day :)

Although midnight doesn't change so drastically, it could cause problems when DST takes effect in certain parts of the world.

**Comment by meezaan** [comment]
@uxai Having a look @ https://aladhan.com/calendar/London/UK. If you select March (which includes DST), it doesn't really cause any problems with DST.

Here is the line of code that calculates it: https://github.com/islamic-network/prayer-times/blob/master/src/PrayerTimes/PrayerTimes.php#L263.

Now, it simply looks times of a particular day and tries to calculate midnight, so it seems to adjust itself properly. Strictly speaking, midnight may fall into the next calendar date, but it applies to the day in question, not the next day. So, midnight for March 12 may fall at 1:00 am on March 13, but it's still the middle of the night of March 12.

So whilst there definitely needs to be a fix in the API with regard to the iso8601 format, I'm trying to actually find a scenario where you think it will cause incorrect timings to appear somewhere (because that's actually of concern to me).

**Comment by meezaan** [comment]
@uxai This is now done. The fix should be available once the deployment completes in the next couple of minutes.
