### ISSUE TITLE
Why forcing a high latitude adjustment method?

### ISSUE THREAD

**Issue by maherahmed** [islamic-network/api.aladhan.com#76]
AlsalamuAlykom,

Why forcing a higher latitude adjustment method? How to get the time without high latitude adjustment?

https://github.com/islamic-network/api.aladhan.com/blob/d1d74175203ee22f9b1c16225bf041d390fdfbe3/api/Utils/Request.php#L48

**Comment by meezaan** [comment]
3laykum salaam. This code is written 7 years ago, so I'm going to recall from memory that this was done because the angle based method for high latitude adjustment was the default used by Islamic Finder and Muslim Pro, and without it, there always differences in the calculation and everyone felt enormous amount of angst about it.

**Comment by maherahmed** [comment]
Can we add the option to have to no adjustment? (return 0 to use LATITUDE_ADJUSTMENT_METHOD_NONE)

**Comment by maherahmed** [comment]
Great! Works well, thanks!

We can mark this one as closed (Y)
